# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    # configure resolvers
    resolvers :
        # setup the default resolver
        default :
            # use the default web path
            web_path : ~
    # your filter sets are defined here
    filter_sets :
        # use the default cache configuration
        cache : ~

        thumb_1_575:
            quality: 75
            filters:
                thumbnail:
                    size:  [565, 600]
                    mode:  outbound
        
        thumb_1_767:
            quality: 75
            filters:
                thumbnail:
                    size:  [757, 400]
                    mode:  outbound

        thumb_1_991:
            quality: 75
            filters:
                thumbnail:
                    size:  [981, 400]
                    mode:  outbound
        thumb_1_1199:
            quality: 75
            filters:
                thumbnail:
                    size:  [1189, 400]
                    mode:  outbound
        
        defaut_1_575:
            quality: 75
            filters:
                thumbnail:
                    size:  [565, 400]
                    mode:  outbound
        
        defaut_1_767:
            quality: 75
            filters:
                thumbnail:
                    size:  [757, 400]
                    mode:  outbound

        defaut_1_991:
            quality: 75
            filters:
                thumbnail:
                    size:  [981, 400]
                    mode:  outbound
        defaut_1_1199:
            quality: 75
            filters:
                thumbnail:
                    size:  [1189, 400]
                    mode:  outbound
        
        thumb_2_575:
            quality: 75
            filters:
                thumbnail:
                    size:  [200, 200]
                    mode:  outbound
